[book]
authors = ["Virginia Ravenscroft", "Brian Carbone"]
language = "en"
multilingual = false
src = "src"
title = "Shufflrr How-To"
description = "The premiere Presentation Management System"

[output.html]
additional-css = ["fonts.css", "custom.css"]
git-repository-url = "https://github.com/shufflrr/userguide"
git-repository-icon = "fa-github"
cname = "howto.shufflrr.com"

[output.html.print]
enable = false

[build]
build-dir = "docs"
